export const dataArray = [
  { id: 1, value: "1", text: "Manufacturing", disable: true, position: 1 },
  {
    id: 2,
    value: "19",
    text: "Construction materials",
    disable: false,
    position: 2,
  },
  {
    id: 3,
    value: "18",
    text: "Electronics and Optics",
    disable: false,
    position: 2,
  },
  { id: 4, value: "6", text: "Food and Beverage", disable: true, position: 2 },
  {
    id: 5,
    value: "342",
    text: "Bakery & confectionery products",
    disable: false,
    position: 3,
  },
  { id: 6, value: "43", text: "Beverages", disable: false, position: 3 },
  {
    id: 7,
    value: "42",
    text: "Fish & fish products",
    disable: false,
    position: 3,
  },
  {
    id: 8,
    value: "40",
    text: "Meat & meat products",
    disable: false,
    position: 3,
  },
  {
    id: 9,
    value: "39",
    text: "Milk & dairy products",
    disable: false,
    position: 3,
  },
  { id: 10, value: "437", text: "Other", disable: false, position: 3 },
  {
    id: 11,
    value: "378",
    text: "Sweets & snack food",
    disable: false,
    position: 3,
  },
  { id: 12, value: "13", text: "Furniture", disable: true, position: 2 },
  { id: 13, value: "389", text: "Bathroom/sauna", disable: false, position: 3 },
  { id: 14, value: "385", text: "Bedroom", disable: false, position: 3 },
  {
    id: 15,
    value: "390",
    text: "Children’s room",
    disable: false,
    position: 3,
  },
  { id: 16, value: "98", text: "Kitchen", disable: false, position: 3 },
  { id: 17, value: "101", text: "Living room", disable: false, position: 3 },
  { id: 18, value: "392", text: "Office", disable: false, position: 3 },
  {
    id: 19,
    value: "394",
    text: "Other (Furniture)",
    disable: false,
    position: 3,
  },
  { id: 20, value: "341", text: "Outdoor", disable: false, position: 3 },
  {
    id: 21,
    value: "99",
    text: "Project furniture",
    disable: false,
    position: 3,
  },
  { id: 22, value: "12", text: "Machinery", disable: true, position: 2 },
  {
    id: 23,
    value: "94",
    text: "Machinery components",
    disable: false,
    position: 3,
  },
  {
    id: 24,
    value: "91",
    text: "Machinery equipment/tools",
    disable: false,
    position: 3,
  },
  {
    id: 25,
    value: "224",
    text: "Manufacture of machinery",
    disable: false,
    position: 3,
  },
  { id: 26, value: "97", text: "Maritime", disable: true, position: 3 },
  {
    id: 27,
    value: "271",
    text: "Aluminium and steel workboats",
    disable: false,
    position: 4,
  },
  {
    id: 28,
    value: "269",
    text: "Boat/Yacht building",
    disable: false,
    position: 4,
  },
  {
    id: 29,
    value: "230",
    text: "Ship repair and conversion",
    disable: false,
    position: 4,
  },
  {
    id: 30,
    value: "93",
    text: "Metal structures",
    disable: false,
    position: 3,
  },
  { id: 31, value: "508", text: "Other", disable: false, position: 3 },
  {
    id: 32,
    value: "227",
    text: "Repair and maintenance service",
    disable: false,
    position: 3,
  },
  { id: 33, value: "11", text: "Metalworking", disable: true, position: 2 },
  {
    id: 34,
    value: "67",
    text: "Construction of metal structures",
    disable: false,
    position: 3,
  },
  {
    id: 35,
    value: "263",
    text: "Houses and buildings",
    disable: false,
    position: 3,
  },
  { id: 36, value: "267", text: "Metal products", disable: false, position: 3 },
  { id: 37, value: "542", text: "Metal works", disable: true, position: 3 },
  { id: 38, value: "75", text: "CNC-machining", disable: false, position: 4 },
  {
    id: 39,
    value: "62",
    text: "Forgings, Fasteners",
    disable: false,
    position: 4,
  },
  {
    id: 40,
    value: "69",
    text: "Gas, Plasma, Laser cutting",
    disable: false,
    position: 4,
  },
  {
    id: 41,
    value: "66",
    text: "MIG, TIG, Aluminum welding",
    disable: false,
    position: 4,
  },
  {
    id: 42,
    value: "9",
    text: "Plastic and Rubber",
    disable: true,
    position: 2,
  },
  { id: 43, value: "54", text: "Packaging", disable: false, position: 3 },
  { id: 44, value: "556", text: "Plastic goods", disable: false, position: 3 },
  {
    id: 45,
    value: "559",
    text: "Plastic processing technology",
    disable: true,
    position: 3,
  },
  { id: 46, value: "55", text: "Blowing", disable: false, position: 4 },
  { id: 47, value: "57", text: "Moulding", disable: false, position: 4 },
  {
    id: 48,
    value: "53",
    text: "Plastics welding and processing",
    disable: false,
    position: 4,
  },
  {
    id: 49,
    value: "560",
    text: "Plastic profiles",
    disable: false,
    position: 3,
  },
  { id: 50, value: "5", text: "Printing", disable: true, position: 2 },
  { id: 51, value: "148", text: "Advertising", disable: false, position: 3 },
  {
    id: 52,
    value: "150",
    text: "Book/Periodicals printing",
    disable: false,
    position: 3,
  },
  {
    id: 53,
    value: "145",
    text: "Labelling and packaging printing",
    disable: false,
    position: 3,
  },
  {
    id: 54,
    value: "7",
    text: "Textile and Clothing",
    disable: true,
    position: 2,
  },
  { id: 55, value: "44", text: "Clothing", disable: false, position: 3 },
  { id: 56, value: "45", text: "Textile", disable: false, position: 3 },
  { id: 57, value: "8", text: "Wood", disable: true, position: 2 },
  { id: 58, value: "337", text: "Other (Wood)", disable: false, position: 3 },
  {
    id: 59,
    value: "51",
    text: "Wooden building materials",
    disable: false,
    position: 3,
  },
  { id: 60, value: "47", text: "Wooden houses", disable: false, position: 3 },
  { id: 61, value: "3", text: "Other", disable: true, position: 1 },
  {
    id: 62,
    value: "37",
    text: "Creative industries",
    disable: false,
    position: 2,
  },
  {
    id: 63,
    value: "29",
    text: "Energy technology",
    disable: false,
    position: 2,
  },
  { id: 64, value: "33", text: "Environment", disable: false, position: 2 },
  { id: 65, value: "2", text: "Service", disable: true, position: 1 },
  {
    id: 66,
    value: "25",
    text: "Business services",
    disable: false,
    position: 2,
  },
  { id: 67, value: "35", text: "Engineering", disable: false, position: 2 },
  {
    id: 68,
    value: "28",
    text: "Information Technology and Telecommunications",
    disable: true,
    position: 2,
  },
  {
    id: 69,
    value: "581",
    text: "Data processing, Web portals, E-marketing",
    disable: false,
    position: 3,
  },
  {
    id: 70,
    value: "576",
    text: "Programming, Consultancy",
    disable: false,
    position: 3,
  },
  {
    id: 71,
    value: "121",
    text: "Software, Hardware",
    disable: false,
    position: 3,
  },
  {
    id: 72,
    value: "122",
    text: "Telecommunications",
    disable: false,
    position: 3,
  },
  { id: 73, value: "22", text: "Tourism", disable: false, position: 2 },
  {
    id: 74,
    value: "141",
    text: "Translation services",
    disable: false,
    position: 2,
  },
  {
    id: 75,
    value: "21",
    text: "Transport and Logistics",
    disable: true,
    position: 2,
  },
  { id: 76, value: "111", text: "Air", disable: false, position: 3 },
  { id: 77, value: "114", text: "Rail", disable: false, position: 3 },
  { id: 78, value: "112", text: "Road", disable: false, position: 3 },
  { id: 79, value: "113", text: "Water", disable: false, position: 3 },
];
